version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  scraper:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
